### PR TITLE
fixing category schema and passing props between home and products li…

### PR DESCRIPTION
**Pull request by hassanidris**
…sting

### CODE REVIEW

**Comment by hassanidris** [comment]
This was only for fixing the schema after merging I will start working on the Cart component

**Review by Quantinx — COMMENTED** [review]
This is what we worked on together?

**Review by Quantinx — COMMENTED** [review]
Make sure you clear git history as we can still see the .env

**Review by Quantinx — APPROVED** [review]
Approved - please ensure API keys is regenerated as any scraper will have got hold of it by now.

**Comment by hassanidris** [comment]
Yah I removed it using this below command:
`git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch .env" HEAD`

**Pull request merged**
